[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gui"
path = "src/main.rs"


[dependencies]
gpui.workspace = true
ui.workspace = true
ui_input.workspace = true
vim.workspace = true
editor.workspace = true
