[package]
name = "resto"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "resto http client"
homepage = "https://github.com/tednaaa/resto"
repository = "https://github.com/tednaaa/resto"
readme = "README.md"
keywords = ["tui", "http_client"]

# [lints.clippy]
# pedantic = "warn"
# nursery = "warn"
# unwrap_used = "warn"
# expect_used = "warn"
# panic = "warn"
# missing_docs_in_private_items = "warn"
# missing_errors_doc = "warn"
# missing_panics_doc = "warn"
# missing_safety_doc = "warn"

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.5.38", features = ["derive"] }
uuid = { version = "1.17.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
